In [1]:
import pandas as pd
import numpy as np

In [49]:
# df = pd.read_csv('OPENDATA_BOOKING_CALL_A_BIKE.csv',sep=";")

In [12]:
# df.head()

,BOOKING_HAL_ID,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_BOOKING,DATE_FROM,DATE_UNTIL,COMPUTE_EXTRA_BOOKING_FEE,TRAVERSE_USE,DISTANCE,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
0,21366843,51000,143517,A821059B555C7764A2FF801180874A2FCB326222,2014-01-01 00:34:54,2014-01-01 00:34:54,2014-01-01 00:50:14,Nein,Nein,0.0,U-Bahn Baumwall,214170.0,Mönckebergstraße / Rosenstraße,131880.0,Standort,Hamburg,iPhone SRH
1,21367069,51000,119830,1EBC930DB407ACEAE2FDE23A6CA40492EA3DFBB2,2014-01-01 01:39:55,2014-01-01 01:39:55,2014-01-01 01:57:27,Nein,Nein,0.0,Bahnhof Altona Ost/Max-Brauer-Allee,131646.0,Schulterblatt/Eifflerstraße,131648.0,Standort,Hamburg,Android SRH
2,21367072,51000,143501,7AD2C1B70137479062A6DD73815835986677BB2D,2014-01-01 01:40:20,2014-01-01 01:40:20,2014-01-01 01:53:09,Nein,Nein,0.0,Weidestraße/Biedermannplatz,211922.0,Jarrestraße / Rambatzweg,138376.0,Standort,Hamburg,Techniker HH_119 (-2334-)
3,21367118,51000,117519,A1062EF019B4E3E71C551572F1B284D55440E3C4,2014-01-01 01:56:00,2014-01-01 01:56:00,2014-01-01 01:56:41,Nein,Nein,0.0,Große Bergstraße / Jessenstraße,131649.0,Große Bergstraße / Jessenstraße,131649.0,Standort,Hamburg,Terminal HH_46 (-2115-)
4,21367155,51000,108641,4F4F752203EA6FC872D576E9289C4E1B362E16F6,2014-01-01 02:05:55,2014-01-01 02:05:55,2014-01-01 02:13:49,Nein,Nein,0.0,Mundsburg / Schürbeker Straße,140799.0,Bartholomäusstraße/Beim Alten Schützenhof,211923.0,Standort,Hamburg,iPhone SRH

In [14]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16228298 entries, 0 to 16228297
Data columns (total 17 columns):
BOOKING_HAL_ID               int64
CATEGORY_HAL_ID              int64
VEHICLE_HAL_ID               int64
CUSTOMER_HAL_ID              object
DATE_BOOKING                 object
DATE_FROM                    object
DATE_UNTIL                   object
COMPUTE_EXTRA_BOOKING_FEE    object
TRAVERSE_USE                 object
DISTANCE                     float64
START_RENTAL_ZONE            object
START_RENTAL_ZONE_HAL_ID     float64
END_RENTAL_ZONE              object
END_RENTAL_ZONE_HAL_ID       float64
RENTAL_ZONE_HAL_SRC          object
CITY_RENTAL_ZONE             object
TECHNICAL_INCOME_CHANNEL     object
dtypes: float64(3), int64(3), object(11)
memory usage: 2.1+ GB

In [15]:
# df['date'] = pd.to_datetime(df['DATE_BOOKING'])

In [26]:
# df['date'].head()

0   2014-01-01 00:34:54
1   2014-01-01 01:39:55
2   2014-01-01 01:40:20
3   2014-01-01 01:56:00
4   2014-01-01 02:05:55
Name: date, dtype: datetime64[ns]

In [28]:
# df.index = df['date']

In [29]:
# del df['date']

In [31]:
# df.head()

,BOOKING_HAL_ID,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_BOOKING,DATE_FROM,DATE_UNTIL,COMPUTE_EXTRA_BOOKING_FEE,TRAVERSE_USE,DISTANCE,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
date,,,,,,,,,,,,,,,,,
2014-01-01 00:34:54,21366843,51000,143517,A821059B555C7764A2FF801180874A2FCB326222,2014-01-01 00:34:54,2014-01-01 00:34:54,2014-01-01 00:50:14,Nein,Nein,0.0,U-Bahn Baumwall,214170.0,Mönckebergstraße / Rosenstraße,131880.0,Standort,Hamburg,iPhone SRH
2014-01-01 01:39:55,21367069,51000,119830,1EBC930DB407ACEAE2FDE23A6CA40492EA3DFBB2,2014-01-01 01:39:55,2014-01-01 01:39:55,2014-01-01 01:57:27,Nein,Nein,0.0,Bahnhof Altona Ost/Max-Brauer-Allee,131646.0,Schulterblatt/Eifflerstraße,131648.0,Standort,Hamburg,Android SRH
2014-01-01 01:40:20,21367072,51000,143501,7AD2C1B70137479062A6DD73815835986677BB2D,2014-01-01 01:40:20,2014-01-01 01:40:20,2014-01-01 01:53:09,Nein,Nein,0.0,Weidestraße/Biedermannplatz,211922.0,Jarrestraße / Rambatzweg,138376.0,Standort,Hamburg,Techniker HH_119 (-2334-)
2014-01-01 01:56:00,21367118,51000,117519,A1062EF019B4E3E71C551572F1B284D55440E3C4,2014-01-01 01:56:00,2014-01-01 01:56:00,2014-01-01 01:56:41,Nein,Nein,0.0,Große Bergstraße / Jessenstraße,131649.0,Große Bergstraße / Jessenstraße,131649.0,Standort,Hamburg,Terminal HH_46 (-2115-)
2014-01-01 02:05:55,21367155,51000,108641,4F4F752203EA6FC872D576E9289C4E1B362E16F6,2014-01-01 02:05:55,2014-01-01 02:05:55,2014-01-01 02:13:49,Nein,Nein,0.0,Mundsburg / Schürbeker Straße,140799.0,Bartholomäusstraße/Beim Alten Schützenhof,211923.0,Standort,Hamburg,iPhone SRH

In [39]:
# creating new dataframe

# df['2016-01-01':'2016-12-31'].to_csv('2016_Call_a_bike.csv', sep=',', encoding='utf-8')
# df['2017-01-01':].to_csv('2017_Call_a_bike.csv', sep=',', encoding='utf-8')

In [45]:
# df_2016.head()

,BOOKING_HAL_ID,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_BOOKING,DATE_FROM,DATE_UNTIL,COMPUTE_EXTRA_BOOKING_FEE,TRAVERSE_USE,DISTANCE,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
date,,,,,,,,,,,,,,,,,
2016-01-01 00:44:49,34948004,51000,108647,0BFC9CA3CA75AEAE16A6BF86913AF5D8613B20BD,2016-01-01 00:44:49,2016-01-01 00:44:49,2016-01-01 01:13:37,Nein,Nein,0.0,Überseering/Mexikoring,213687.0,Bebelallee/Meenkwiese,213855.0,Standort,Hamburg,Android SRH
2016-01-01 00:31:46,34947949,51000,108371,48A88184B22E7171E8A03E34FF32E761DD83CA92,2016-01-01 00:31:46,2016-01-01 00:31:46,2016-01-01 00:58:49,Nein,Nein,0.0,Stadthausbrücke / Neuer Wall,138379.0,Goldbekplatz / Semperstraße,140796.0,Standort,Hamburg,iPhone SRH
2016-01-01 00:38:37,34947974,51000,119829,F84BCAB7154C63B9E4A7E7EA13BB4FA493539A12,2016-01-01 00:38:37,2016-01-01 00:38:37,2016-01-01 00:49:50,Nein,Nein,0.0,Jungfernstieg / Ballindamm,131879.0,Hauptbahnhof Ost / Hachmannplatz,131873.0,Standort,Hamburg,iPhone CAB
2016-01-01 01:11:00,34948134,51000,116810,7D8127DA8F382BF2C3A8FD31202D46A150A513AE,2016-01-01 01:11:00,2016-01-01 01:11:00,2016-01-01 02:26:23,Nein,Nein,0.0,Hudtwalckerstraße / Bebelallee,138378.0,Kellinghusenstraße / Loogeplatz,140795.0,Standort,Hamburg,Terminal HH_72 (-2369-)
2016-01-01 01:06:17,34948107,51000,120345,AEE37262F04CB04681868F6E8CEE2D7F9CDA6997,2016-01-01 01:06:17,2016-01-01 01:06:17,2016-01-01 01:15:16,Nein,Nein,0.0,Bahnhof Dammtor Nord // Theodor-Heuss-Platz,131883.0,Feldstraße / Marktstraße,244093.0,Standort,Hamburg,Android SRH

In [2]:
df_2016 = pd.read_csv('2016_Call_a_bike.csv')

In [3]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5702575 entries, 0 to 5702574
Data columns (total 18 columns):
date                         object
BOOKING_HAL_ID               int64
CATEGORY_HAL_ID              int64
VEHICLE_HAL_ID               int64
CUSTOMER_HAL_ID              object
DATE_BOOKING                 object
DATE_FROM                    object
DATE_UNTIL                   object
COMPUTE_EXTRA_BOOKING_FEE    object
TRAVERSE_USE                 object
DISTANCE                     float64
START_RENTAL_ZONE            object
START_RENTAL_ZONE_HAL_ID     float64
END_RENTAL_ZONE              object
END_RENTAL_ZONE_HAL_ID       float64
RENTAL_ZONE_HAL_SRC          object
CITY_RENTAL_ZONE             object
TECHNICAL_INCOME_CHANNEL     object
dtypes: float64(3), int64(3), object(12)
memory usage: 783.1+ MB

In [30]:
df_2016[df_2016.TECHNICAL_INCOME_CHANNEL == 'Android SRH'].shape

(641988, 18)

In [25]:
df_2016.CITY_RENTAL_ZONE.unique()

array(['Hamburg', 'Kassel', 'Darmstadt', 'Frankfurt am Main', 'Marburg',
       'Berlin', 'Stuttgart', 'Köln', 'München', 'Wiesbaden',
       'Rüsselsheim', 'Weimar', 'Mannheim', 'Karlsruhe', 'Bonn', 'Halle',
       'Lübeck', 'Baden-Baden', 'Bamberg', 'Göttingen', 'Flugh. Frankfurt',
       'Oberhausen', 'Freiburg', 'Kiel', 'Würzburg', 'Erlangen',
       'Düsseldorf', 'Fulda', 'Troisdorf', 'Oldenburg (Oldb)',
       'Heidelberg', 'Warnemünde', 'Gütersloh', 'Bremen', 'Mainz',
       'Saarbrücken', 'Hannover', 'Aschaffenburg', 'Rostock', 'Hanau',
       'Ingolstadt', 'Braunschweig', 'Magdeburg', 'Kaiserslautern',
       'Bielefeld', 'Hennef'], dtype=object)

In [27]:
df_2016.CITY_RENTAL_ZONE.unique().shape

(46,)

In [45]:
df_2016[df_2016.RENTAL_ZONE_HAL_SRC != 'Standort'].shape

(103756, 18)

In [43]:
df_2016.shape

(5702575, 18)

In [44]:
df_2016.dropna(how='any').shape

(4276986, 18)

In [46]:
5702575 - 4276986

1425589

In [49]:
df_2016.CUSTOMER_HAL_ID.unique().shape

(267115,)

In [52]:
df_2016.TRAVERSE_USE.unique()

array(['Nein'], dtype=object)

In [54]:
df_2016.drop(['COMPUTE_EXTRA_BOOKING_FEE', 'TRAVERSE_USE'], axis=1, inplace=True)

In [65]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5702575 entries, 0 to 5702574
Data columns (total 15 columns):
date                        object
BOOKING_HAL_ID              int64
CATEGORY_HAL_ID             int64
VEHICLE_HAL_ID              int64
CUSTOMER_HAL_ID             object
DATE_BOOKING                object
DATE_FROM                   object
DATE_UNTIL                  object
START_RENTAL_ZONE           object
START_RENTAL_ZONE_HAL_ID    float64
END_RENTAL_ZONE             object
END_RENTAL_ZONE_HAL_ID      float64
RENTAL_ZONE_HAL_SRC         object
CITY_RENTAL_ZONE            object
TECHNICAL_INCOME_CHANNEL    object
dtypes: float64(2), int64(3), object(10)
memory usage: 652.6+ MB

In [57]:
df_2016.BOOKING_HAL_ID.unique().shape

(5702575,)

In [60]:
df_2016.CATEGORY_HAL_ID.unique()

array([51000, 53000, 50000, 50001])

In [63]:
df_2016.VEHICLE_HAL_ID.unique().shape

(10527,)

In [64]:
df_2016.drop(['DISTANCE'], axis=1, inplace=True)

In [66]:
df_2016.head(10)

,date,BOOKING_HAL_ID,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_BOOKING,DATE_FROM,DATE_UNTIL,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
0,2016-01-01 00:44:49,34948004,51000,108647,0BFC9CA3CA75AEAE16A6BF86913AF5D8613B20BD,2016-01-01 00:44:49,2016-01-01 00:44:49,2016-01-01 01:13:37,Überseering/Mexikoring,213687.0,Bebelallee/Meenkwiese,213855.0,Standort,Hamburg,Android SRH
1,2016-01-01 00:31:46,34947949,51000,108371,48A88184B22E7171E8A03E34FF32E761DD83CA92,2016-01-01 00:31:46,2016-01-01 00:31:46,2016-01-01 00:58:49,Stadthausbrücke / Neuer Wall,138379.0,Goldbekplatz / Semperstraße,140796.0,Standort,Hamburg,iPhone SRH
2,2016-01-01 00:38:37,34947974,51000,119829,F84BCAB7154C63B9E4A7E7EA13BB4FA493539A12,2016-01-01 00:38:37,2016-01-01 00:38:37,2016-01-01 00:49:50,Jungfernstieg / Ballindamm,131879.0,Hauptbahnhof Ost / Hachmannplatz,131873.0,Standort,Hamburg,iPhone CAB
3,2016-01-01 01:11:00,34948134,51000,116810,7D8127DA8F382BF2C3A8FD31202D46A150A513AE,2016-01-01 01:11:00,2016-01-01 01:11:00,2016-01-01 02:26:23,Hudtwalckerstraße / Bebelallee,138378.0,Kellinghusenstraße / Loogeplatz,140795.0,Standort,Hamburg,Terminal HH_72 (-2369-)
4,2016-01-01 01:06:17,34948107,51000,120345,AEE37262F04CB04681868F6E8CEE2D7F9CDA6997,2016-01-01 01:06:17,2016-01-01 01:06:17,2016-01-01 01:15:16,Bahnhof Dammtor Nord // Theodor-Heuss-Platz,131883.0,Feldstraße / Marktstraße,244093.0,Standort,Hamburg,Android SRH
5,2016-01-01 01:24:50,34948223,53000,117442,93FB6B477B0D8279831D2B4BDE4F07A235790420,2016-01-01 01:24:50,2016-01-01 01:24:50,2016-01-01 01:35:57,Hauptbahnhof / Rainer-Dierichs-Platz,204812.0,Uni-Kassel / Diagonale,204815.0,Standort,Kassel,Android KON
6,2016-01-01 00:08:54,34947894,50000,107059,6493DD3449E808F4EEF906BE9652CB90AFDF1047,2016-01-01 00:08:54,2016-01-01 00:08:54,2016-01-01 00:23:57,Darmstadt Hbf,128496.0,Darmstadtium,246251.0,Standort,Darmstadt,iPhone CAB
7,2016-01-01 00:27:53,34947937,50000,107059,BAE9525F74EFEDE89BD181AC8BEA45AF1D189EBB,2016-01-01 00:27:53,2016-01-01 00:27:53,2016-01-01 00:38:33,Darmstadtium,246251.0,NaN,NaN,Standort,Darmstadt,iPhone CAB
8,2016-01-01 00:30:33,34947942,51000,119362,FBB1BE2E1A9546984B757CFF3452F9EEF4CBC1BC,2016-01-01 00:30:33,2016-01-01 00:30:33,2016-01-01 00:48:01,Alter Wall/Adolphsbrücke,158204.0,Sievekingsallee/Sievekingdamm,244936.0,Standort,Hamburg,iPhone SRH
9,2016-01-01 01:06:19,34948109,51000,109225,CBF6549804C19E7C0ECB715896867CDFD68971A0,2016-01-01 01:06:19,2016-01-01 01:06:19,2016-01-01 01:15:11,Bahnhof Dammtor Nord // Theodor-Heuss-Platz,131883.0,Feldstraße / Marktstraße,244093.0,Standort,Hamburg,IVR

In [67]:
df_2016.END_RENTAL_ZONE.unique().shape

(824,)

In [68]:
df_2016.END_RENTAL_ZONE_HAL_ID.unique().shape

(14190,)

In [69]:
df_2016.START_RENTAL_ZONE.unique().shape

(822,)

In [70]:
df_2016.START_RENTAL_ZONE_HAL_ID.unique().shape

(13951,)

In [75]:
df_2016.index = df_2016['date']
del df_2016['date']
del df_2016['BOOKING_HAL_ID']

In [76]:
df_2016.head()

,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_BOOKING,DATE_FROM,DATE_UNTIL,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
date,,,,,,,,,,,,,
2016-01-01 00:44:49,51000,108647,0BFC9CA3CA75AEAE16A6BF86913AF5D8613B20BD,2016-01-01 00:44:49,2016-01-01 00:44:49,2016-01-01 01:13:37,Überseering/Mexikoring,213687.0,Bebelallee/Meenkwiese,213855.0,Standort,Hamburg,Android SRH
2016-01-01 00:31:46,51000,108371,48A88184B22E7171E8A03E34FF32E761DD83CA92,2016-01-01 00:31:46,2016-01-01 00:31:46,2016-01-01 00:58:49,Stadthausbrücke / Neuer Wall,138379.0,Goldbekplatz / Semperstraße,140796.0,Standort,Hamburg,iPhone SRH
2016-01-01 00:38:37,51000,119829,F84BCAB7154C63B9E4A7E7EA13BB4FA493539A12,2016-01-01 00:38:37,2016-01-01 00:38:37,2016-01-01 00:49:50,Jungfernstieg / Ballindamm,131879.0,Hauptbahnhof Ost / Hachmannplatz,131873.0,Standort,Hamburg,iPhone CAB
2016-01-01 01:11:00,51000,116810,7D8127DA8F382BF2C3A8FD31202D46A150A513AE,2016-01-01 01:11:00,2016-01-01 01:11:00,2016-01-01 02:26:23,Hudtwalckerstraße / Bebelallee,138378.0,Kellinghusenstraße / Loogeplatz,140795.0,Standort,Hamburg,Terminal HH_72 (-2369-)
2016-01-01 01:06:17,51000,120345,AEE37262F04CB04681868F6E8CEE2D7F9CDA6997,2016-01-01 01:06:17,2016-01-01 01:06:17,2016-01-01 01:15:16,Bahnhof Dammtor Nord // Theodor-Heuss-Platz,131883.0,Feldstraße / Marktstraße,244093.0,Standort,Hamburg,Android SRH

In [79]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5702575 entries, 2016-01-01 00:44:49 to 2016-12-31 23:54:05
Data columns (total 12 columns):
CATEGORY_HAL_ID             int64
VEHICLE_HAL_ID              int64
CUSTOMER_HAL_ID             object
DATE_FROM                   object
DATE_UNTIL                  object
START_RENTAL_ZONE           object
START_RENTAL_ZONE_HAL_ID    float64
END_RENTAL_ZONE             object
END_RENTAL_ZONE_HAL_ID      float64
RENTAL_ZONE_HAL_SRC         object
CITY_RENTAL_ZONE            object
TECHNICAL_INCOME_CHANNEL    object
dtypes: float64(2), int64(2), object(8)
memory usage: 565.6+ MB

In [78]:
del df_2016['DATE_BOOKING']

In [86]:
df_2016.index = pd.to_datetime(df_2016['DATE_FROM'])
df_2016.index.names = ['Date']

In [87]:
df_2016.head()

,CATEGORY_HAL_ID,VEHICLE_HAL_ID,CUSTOMER_HAL_ID,DATE_FROM,DATE_UNTIL,START_RENTAL_ZONE,START_RENTAL_ZONE_HAL_ID,END_RENTAL_ZONE,END_RENTAL_ZONE_HAL_ID,RENTAL_ZONE_HAL_SRC,CITY_RENTAL_ZONE,TECHNICAL_INCOME_CHANNEL
Date,,,,,,,,,,,,
2016-01-01 00:44:49,51000,108647,0BFC9CA3CA75AEAE16A6BF86913AF5D8613B20BD,2016-01-01 00:44:49,2016-01-01 01:13:37,Überseering/Mexikoring,213687.0,Bebelallee/Meenkwiese,213855.0,Standort,Hamburg,Android SRH
2016-01-01 00:31:46,51000,108371,48A88184B22E7171E8A03E34FF32E761DD83CA92,2016-01-01 00:31:46,2016-01-01 00:58:49,Stadthausbrücke / Neuer Wall,138379.0,Goldbekplatz / Semperstraße,140796.0,Standort,Hamburg,iPhone SRH
2016-01-01 00:38:37,51000,119829,F84BCAB7154C63B9E4A7E7EA13BB4FA493539A12,2016-01-01 00:38:37,2016-01-01 00:49:50,Jungfernstieg / Ballindamm,131879.0,Hauptbahnhof Ost / Hachmannplatz,131873.0,Standort,Hamburg,iPhone CAB
2016-01-01 01:11:00,51000,116810,7D8127DA8F382BF2C3A8FD31202D46A150A513AE,2016-01-01 01:11:00,2016-01-01 02:26:23,Hudtwalckerstraße / Bebelallee,138378.0,Kellinghusenstraße / Loogeplatz,140795.0,Standort,Hamburg,Terminal HH_72 (-2369-)
2016-01-01 01:06:17,51000,120345,AEE37262F04CB04681868F6E8CEE2D7F9CDA6997,2016-01-01 01:06:17,2016-01-01 01:15:16,Bahnhof Dammtor Nord // Theodor-Heuss-Platz,131883.0,Feldstraße / Marktstraße,244093.0,Standort,Hamburg,Android SRH

In [94]:
# date time fix